// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: WebSocketRequest.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace PixiEditor.Extensions.CommonApi.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WebSocketRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public WebSocketOperation Operation { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Headers { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(4)]
        public WebSocketMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebSocketMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public WebSocketMessageType MessageType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum WebSocketOperation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT")]
        Connect = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SEND")]
        Send = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"RECEIVE")]
        Receive = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOSE")]
        Close = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum WebSocketMessageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT")]
        Text = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BINARY")]
        Binary = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
