---
name: Bug Report
description: Report a bug
title: "[BUG]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug! Please remember to
        incude all relevant files such as crash reports, logs and screenshots if
        available.
  - type: textarea
    id: bugdesc
    attributes:
      label: Bug Description
      description: A general description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps how to trigger the issue
      description: Walk us through how we can reproduce this bug. If you don't know
        the exact steps, write down when it happened or any info that could help
        us identify the issue.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - PixiEditor Website
        - Microsoft Store
        - Steam
        - GitHub
        - Linux Package Manager (specify in Additional Context)
        - App Store
        - Built from source
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version Channel
      description: What channel of PixiEditor are you running?
      options:
        - Stable
        - Development
      default: 0
    validations:
      required: true
  - type: input
    id: versionNum
    attributes:
      label: Version Number
      description: What version of PixiEditor are you running?
      placeholder: 2.0.0.64
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: On what operating system did you encounter the bug?
      options:
        - Windows
        - MacOS
        - Linux
      default: 0
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Additional context that could help us fix the issue.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/PixiEditor/PixiEditor/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
