using PixiEditor.Helpers;

[assembly:LocalizedKey("HARDNESS_SETTING", "Used as a blackboard variable within brush inside built-in .pixi files.")]
[assembly:LocalizedKey("SPACING_SETTING", "Used as a blackboard variable within brush inside built-in .pixi files.")]
[assembly:LocalizedKey("COLOR_PICKER_COLOR", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_END_X", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_END_Y", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_GRADIENT", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_GRADIENT_CONICAL", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_GRADIENT_LINEAR", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_GRADIENT_RADIAL", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_OFFSET", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_START_X", "Used inside the Color Picker")]
[assembly:LocalizedKey("COLOR_PICKER_START_Y", "Used inside the Color Picker")]
[assembly:LocalizedKey("TAB_CLOSE", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_CLOSE_ALL", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_CLOSE_OTHERS", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_FLOAT", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_SPLIT_DOWN", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_SPLIT_LEFT", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_SPLIT_RIGHT", "Used inside the PixiDocks")]
[assembly:LocalizedKey("TAB_SPLIT_UP", "Used inside the PixiDocks")]
