using Avalonia.Platform;
using Drawie.Backend.Core;
using PixiEditor.ChangeableDocument.Changeables.Brushes;
using PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.Brushes;
using PixiEditor.ChangeableDocument.Changeables.Interfaces;
using PixiEditor.Models.Handlers;
using PixiEditor.Models.IO;
using PixiEditor.ViewModels.Document.Nodes.Brushes;

namespace PixiEditor.Models.BrushEngine;

internal class Brush : IBrush
{
    public IDocument Document { get; set; }
    IReadOnlyDocument IBrush.Document => Document.AccessInternalReadOnlyDocument();
    public string Name { get; set; }
    public string? FilePath { get; }
    public Guid Id { get; }
    public Texture Preview { get; }

    public Brush(Uri uri)
    {
        Stream stream;
        if (uri.IsFile)
        {
            stream = File.OpenRead(uri.LocalPath);
            FilePath = uri.LocalPath;
        }
        else
        {
            stream = AssetLoader.Open(uri);
        }

        byte[] buffer = new byte[stream.Length];
        stream.ReadExactly(buffer, 0, buffer.Length);
        var doc = Importer.ImportDocument(buffer, null);

        using var graph = doc.ShareGraph();
        BrushOutputNode outputNode =
            graph.TryAccessData().AllNodes.OfType<BrushOutputNode>().FirstOrDefault();
        string name = Path.GetFileNameWithoutExtension(uri.LocalPath);
        if (outputNode != null)
        {
            name = outputNode.BrushName.Value;
            Id = outputNode.Id;
        }
        else
        {
            Id = Guid.NewGuid();
        }

        Name = name;
        Document = doc;
        Preview = ExtractPreview(doc);

        stream.Close();
        stream.Dispose();
    }

    public Brush(string name, IDocument brushDocument)
    {
        Name = name;
        Document = brushDocument;
        FilePath = brushDocument.FullFilePath;
        Id = brushDocument.NodeGraphHandler.AllNodes.OfType<BrushOutputNodeViewModel>().FirstOrDefault()?.Id ?? Guid.NewGuid();
        Preview = ExtractPreview(brushDocument);
    }

    public Brush(string name, IDocument brushDocument, Guid id)
    {
        Name = name;
        Document = brushDocument;
        FilePath = brushDocument.FullFilePath;
        Id = id;
        Preview = ExtractPreview(brushDocument);
    }

    private Texture? ExtractPreview(IDocument brushDocument)
    {
        using var graph = brushDocument.ShareGraph();
        BrushOutputNode outputNode =
            graph.TryAccessData().AllNodes.OfType<BrushOutputNode>().FirstOrDefault();
        if (outputNode != null && outputNode.AutoGeneratedPreview != null)
        {
            return outputNode.AutoGeneratedPreview;
        }

        return null;
    }

    public override string ToString()
    {
        return Name;
    }
}
